# Generated by Django 4.0.3 on 2022-10-16 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('credentials', '0002_alter_customuser_user_type'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='credentials.session'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='student.subject'),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='attendance',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='staff.attendance'),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='feedbackstaff',
            name='staff',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
        ),
        migrations.AddField(
            model_name='leavereportstaff',
            name='staff',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
        ),
        migrations.AddField(
            model_name='notificationstaff',
            name='staff',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
        ),
        migrations.AddField(
            model_name='staff',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='staff.course'),
        ),
    ]
