# Generated by Django 4.0.3 on 2022-10-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Sponsor'), (2, 'Staff'), (3, 'Student')], default=3, max_length=1),
        ),
    ]
